### ISSUE TITLE
Chat on Tabular Data还是有问题，在最后一步，请教下大佬

### ISSUE THREAD

**Issue by rxmao** [tablegpt/tablegpt-agent#149]
![20241209-101416](https://github.com/user-attachments/assets/aefe5225-a041-449b-98ee-c97db7477c6e)

**Comment by edwardzjl** [comment]
请提供一下读取文件工作流的输出

**Comment by rxmao** [comment]
> 请提供一下读取文件工作流的输出


代码


Python 3 (ipykernel)
cd /work/home/rxmaopku/data/mrx/MLLM/tablegpt-agent/src
/work/home/rxmaopku/data/mrx/MLLM/tablegpt-agent/src
/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]
python -m asyncio
  Cell In[2], line 1
    python -m asyncio
              ^
SyntaxError: invalid syntax
import asyncio
from langchain_openai import ChatOpenAI
from pybox import LocalPyBoxManager
from tablegpt.agent import create_tablegpt_graph
from tablegpt import DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR

llm = ChatOpenAI(openai_api_base="http://localhost:8000/v1", openai_api_key="123456", model_name="TableGPT2-7B")
pybox_manager = LocalPyBoxManager(profile_dir=DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR)

agent = create_tablegpt_graph(
    llm=llm,
    pybox_manager=pybox_manager,
)
/tmp/ipykernel_5388/2779787291.py:3: UserWarning: Unable to find tablegpt ipykernel. If you need to use a local kernel,
please use `pip install -U tablegpt-agent[local]` to install the necessary dependencies.
For more issues, please submit an issue to us https://github.com/tablegpt/tablegpt-agent/issues.
  from tablegpt.agent import create_tablegpt_graph
from datetime import date
from langchain_core.messages import HumanMessage

message = HumanMessage(content="Hi")

_input = {
    "messages": [message],
    "parent_id": "some-parent-id",
    "date": date.today(),
}

response = await agent.ainvoke(_input)
response["messages"]
[HumanMessage(content='Hi', additional_kwargs={}, response_metadata={}, id='f8807c51-68d2-4fa6-9c2d-fdde5147ff1b'),
 AIMessage(content='Hello! How can I assist you today? If you have any specific questions or need help with data analysis, feel free to let me know.', additional_kwargs={'parent_id': 'some-parent-id'}, response_metadata={}, id='89398b12-ce49-48db-bf00-0783885552c2')]
async for event in agent.astream_events(
    input=_input,
    version="v2",
):
    # We ignore irrelevant events here.
    if event["event"] == "on_chat_model_end":
        print(event["data"]["output"])
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from pybox import LocalPyBoxManager
from tablegpt import DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR
from tablegpt.agent import create_tablegpt_graph

llm = ChatOpenAI(openai_api_base="http://localhost:8000/v1", openai_api_key="123456", model_name="TableGPT2-7B")
pybox_manager = LocalPyBoxManager(profile_dir=DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR)
checkpointer = MemorySaver()

agent = create_tablegpt_graph(
    llm=llm,
    pybox_manager=pybox_manager,
    checkpointer=checkpointer,
    session_id="some-session-id", # This is required when using file-reading
)
from typing import TypedDict
from langchain_core.messages import HumanMessage

class Attachment(TypedDict):
    """Contains at least one dictionary with the key filename."""
    filename: str

attachment_msg = HumanMessage(
    content="",
    # Please make sure your iPython kernel can access your filename.
    additional_kwargs={"attachments": [Attachment(filename="titanic.csv")]},
)






from datetime import date
from tablegpt.agent.file_reading import Stage

# Reading and processing files.
response = await agent.ainvoke(
    input={
        "entry_message": attachment_msg,
        "processing_stage": Stage.UPLOADED,
        "messages": [attachment_msg],
        "parent_id": "some-parent-id1",
        "date": date.today(),
    },
    config={
        # Using checkpointer requires binding thread_id at runtime.
        "configurable": {"thread_id": "some-thread-id"},
    },
)
response["messages"]
[HumanMessage(content='', additional_kwargs={'attachments': [{'filename': 'titanic.csv'}]}, response_metadata={}, id='0e904a58-bece-4940-988b-22916933f202'),
 AIMessage(content="我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查看 NaN 情况和数据类型。\n```python\n# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)\n```", additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '我已经收到您的数据文件，我需要查看文件内容以对数据集有一个初步的了解。首先我会读取数据到 `df` 变量中，并通过 `df.info` 查看 NaN 情况和数据类型。', 'action': {'tool': 'python', 'tool_input': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'model_type': None}, response_metadata={}, id='4c6f098d-f917-411c-b78d-35e50a012eaa', tool_calls=[{'name': 'python', 'args': {'query': "# Load the data into a DataFrame\ndf = read_df('titanic.csv')\n\n# Remove leading and trailing whitespaces in column names\ndf.columns = df.columns.str.strip()\n\n# Remove rows and columns that contain only empty values\ndf = df.dropna(how='all').dropna(axis=1, how='all')\n\n# Get the basic information of the dataset\ndf.info(memory_usage=False)"}, 'id': 'e6d5e908-34e8-45c9-b55e-744c49b3af96', 'type': 'tool_call'}]),
 ToolMessage(content=[{'type': 'text', 'text': "```pycon\n---------------------------------------------------------------------------\nNameError                                 Traceback (most recent call last)\nCell In[1], line 2\n      1 # Load the data into a DataFrame\n----> 2 df = read_df('titanic.csv')\n      4 # Remove leading and trailing whitespaces in column names\n      5 df.columns = df.columns.str.strip()\n\nNameError: name 'read_df' is not defined\n```"}], name='python', id='97b4049d-1b13-4335-a988-cb5465c1cd1c', tool_call_id='e6d5e908-34e8-45c9-b55e-744c49b3af96', artifact=[]),
 AIMessage(content='接下来我将用 `df.head(5)` 来查看数据集的前 5 行。\n```python\n# Show the first 5 rows to understand the structure\ndf.head(5)\n```', additional_kwargs={'parent_id': 'some-parent-id1', 'thought': '接下来我将用 `df.head(5)` 来查看数据集的前 5 行。', 'action': {'tool': 'python', 'tool_input': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'model_type': None}, response_metadata={}, id='eb6628af-acb0-499a-9f42-11148f3c6439', tool_calls=[{'name': 'python', 'args': {'query': '# Show the first 5 rows to understand the structure\ndf.head(5)'}, 'id': '95f9bcf8-aad3-419e-8ff4-a2955f22f032', 'type': 'tool_call'}]),
 ToolMessage(content=[{'type': 'text', 'text': "```pycon\n---------------------------------------------------------------------------\nNameError                                 Traceback (most recent call last)\nCell In[2], line 2\n      1 # Show the first 5 rows to understand the structure\n----> 2 df.head(5)\n\nNameError: name 'df' is not defined\n```"}], name='python', id='6e9ce516-41a2-42a0-94ff-e9cde7804b78', tool_call_id='95f9bcf8-aad3-419e-8ff4-a2955f22f032', artifact=[]),
 AIMessage(content='我已经了解了数据集 titanic.csv 的基本信息。请问我可以帮您做些什么？', additional_kwargs={'parent_id': 'some-parent-id1'}, response_metadata={}, id='e7c8ef61-5a2b-42c3-b282-91f00395d8c6')]

**Comment by edwardzjl** [comment]
在读取文件的工作流中已经报了错误信息:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[1], line 2
      1 # Load the data into a DataFrame
----> 2 df = read_df('titanic.csv')
      4 # Remove leading and trailing whitespaces in column names
      5 df.columns = df.columns.str.strip()

NameError: name 'read_df' is not defined
```

`read_df` 是 `tablegpt-agent` 在分析数据时必须的一个函数，由 IPython startup script 的形式注入到 IPython kernel 中。
在 `0.2.14` 版本中我们在安装 `tablegpt-agent` 时默认会安装该脚本，并更新了文档。

麻烦你试着更新以下 `tablegpt-agent` (`pip install -U tablegpt-agent[local]`)，并按照最新的文档再尝试一下。

**Comment by rxmao** [comment]
> pip install -U tablegpt-agent[local]

pip install -U tablegpt-agent[local]==0.2.14安装这个版本的？

**Comment by edwardzjl** [comment]
如果你不是 windows 操作系统，不需要指定版本，更新到最新版就行:

```sh
pip install -U tablegpt-agent[local]
```

如果你是 Windows，你无法安装最新版的 tablegpt-agent (见 #153)，你可以显式指定更新到小于 `0.2.17`:

```sh
pip install -U tablegpt-agent[local]<0.2.17
```

**Comment by CRonaldo1997** [comment]
我在那windows下用pip install tablegpt-agent[local]==0.2.14解决了该问题

**Comment by pen-ho** [comment]
你好，执行example的数据分析脚本，报错如下：是我本地部署模型的方式不对吗？
`Traceback (most recent call last):
  File "/Users/penho/Documents/nlp/PythonProject/bm_docqa_v1/test/test_tablegpt_agent.py", line 72, in <module>
    asyncio.run(main())
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/penho/Documents/nlp/PythonProject/bm_docqa_v1/test/test_tablegpt_agent.py", line 58, in main
    async for event in agent.astream_events(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1247, in astream_events
    async for event in event_stream:
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 1006, in _astream_events_implementation_v2
    await task
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 966, in consume_astream
    async for _ in event_streamer.tap_output_aiter(run_id, stream):
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 182, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 78, in anext_impl
    return await __anext__(iterator)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 2274, in astream
    async for _ in runner.atick(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/runner.py", line 444, in atick
    await arun_with_retry(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/retry.py", line 123, in arun_with_retry
    async for _ in task.proc.astream(task.input, config):
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/utils/runnable.py", line 706, in astream
    async for chunk in aiterator:
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 182, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 78, in anext_impl
    return await __anext__(iterator)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform
    async for ichunk in input:
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform
    async for ichunk in input:
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 2274, in astream
    async for _ in runner.atick(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/runner.py", line 444, in atick
    await arun_with_retry(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/retry.py", line 123, in arun_with_retry
    async for _ in task.proc.astream(task.input, config):
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/utils/runnable.py", line 706, in astream
    async for chunk in aiterator:
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 182, in tap_output_aiter
    first = await py_anext(output, default=sentinel)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 78, in anext_impl
    return await __anext__(iterator)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform
    async for ichunk in input:
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform
    async for ichunk in input:
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform
    async for ichunk in input:
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 875, in astream
    yield await self.ainvoke(input, config, **kwargs)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/utils/runnable.py", line 373, in ainvoke
    ret = await self.afunc(*args, **kwargs)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/tablegpt/agent/data_analyzer.py", line 252, in agent_node
    agent_outcome: AgentAction | AgentFinish = await agent.ainvoke(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2923, in ainvoke
    input = await asyncio.create_task(part())
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 298, in ainvoke
    llm_result = await self.agenerate_prompt(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 787, in agenerate_prompt
    return await self.agenerate(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 747, in agenerate
    raise exceptions[0]
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 923, in _agenerate_with_cache
    result = await self._agenerate(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 843, in _agenerate
    response = await self.async_client.create(**payload)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 2000, in create
    return await self._post(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/openai/_base_client.py", line 1767, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/openai/_base_client.py", line 1461, in request
    return await self._request(
  File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/openai/_base_client.py", line 1562, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'detail': [{'type': 'string_type', 'loc': ['body', 'messages', 2, 'tool_calls'], 'msg': 'Input should be a valid string', 'input': [{'type': 'function', 'id': '82c06585-d765-4ebb-a5c8-c3c820880cec', 'function': {'name': 'python', 'arguments': '{"query": "# Load the data into a DataFrame\\ndf = read_df(\'titanic.csv\')\\n\\n# Remove leading and trailing whitespaces in column names\\ndf.columns = df.columns.str.strip()\\n\\n# Remove rows and columns that contain only empty values\\ndf = df.dropna(how=\'all\').dropna(axis=1, how=\'all\')\\n\\n# Get the basic information of the dataset\\ndf.info(memory_usage=False)"}'}}]}, {'type': 'string_type', 'loc': ['body', 'messages', 3, 'content'], 'msg': 'Input should be a valid string', 'input': [{'type': 'text', 'text': "```pycon\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 4 entries, 0 to 3\nData columns (total 8 columns):\n #   Column    Non-Null Count  Dtype  \n---  ------    --------------  -----  \n 0   Pclass    4 non-null      int64  \n 1   Sex       4 non-null      object \n 2   Age       4 non-null      float64\n 3   SibSp     4 non-null      int64  \n 4   Parch     4 non-null      int64  \n 5   Fare      4 non-null      float64\n 6   Embarked  4 non-null      object \n 7   Survived  4 non-null      int64  \ndtypes: float64(2), int64(4), object(2)\n```"}]}, {'type': 'string_type', 'loc': ['body', 'messages', 4, 'tool_calls'], 'msg': 'Input should be a valid string', 'input': [{'type': 'function', 'id': '36cd0e37-700a-422b-b6b9-fe32d6bdbf8d', 'function': {'name': 'python', 'arguments': '{"query": "# Show the first 5 rows to understand the structure\\ndf.head(5)"}'}}]}, {'type': 'string_type', 'loc': ['body', 'messages', 5, 'content'], 'msg': 'Input should be a valid string', 'input': [{'type': 'text', 'text': '```pycon\n   Pclass     Sex   Age  SibSp  Parch    Fare Embarked  Survived\n0       2  female  29.0      0      2  23.000        S         1\n1       3  female  39.0      1      5  31.275        S         0\n2       3    male  26.5      0      0   7.225        C         0\n3       3    male  32.0      0      0  56.496        S         1\n```'}]}]}`

**Comment by pen-ho** [comment]
> 你好，执行example的数据分析脚本，报错如下：是我本地部署模型的方式不对吗？ `` Traceback (most recent call last): File "/Users/penho/Documents/nlp/PythonProject/bm_docqa_v1/test/test_tablegpt_agent.py", line 72, in <module> asyncio.run(main()) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete return future.result() File "/Users/penho/Documents/nlp/PythonProject/bm_docqa_v1/test/test_tablegpt_agent.py", line 58, in main async for event in agent.astream_events( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1247, in astream_events async for event in event_stream: File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 1006, in _astream_events_implementation_v2 await task File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 966, in consume_astream async for _ in event_streamer.tap_output_aiter(run_id, stream): File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 182, in tap_output_aiter first = await py_anext(output, default=sentinel) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 78, in anext_impl return await __anext__(iterator) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 2274, in astream async for _ in runner.atick( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/runner.py", line 444, in atick await arun_with_retry( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/retry.py", line 123, in arun_with_retry async for _ in task.proc.astream(task.input, config): File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/utils/runnable.py", line 706, in astream async for chunk in aiterator: File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 182, in tap_output_aiter first = await py_anext(output, default=sentinel) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 78, in anext_impl return await __anext__(iterator) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform async for ichunk in input: File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform async for ichunk in input: File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 2274, in astream async for _ in runner.atick( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/runner.py", line 444, in atick await arun_with_retry( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/pregel/retry.py", line 123, in arun_with_retry async for _ in task.proc.astream(task.input, config): File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/utils/runnable.py", line 706, in astream async for chunk in aiterator: File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/tracers/event_stream.py", line 182, in tap_output_aiter first = await py_anext(output, default=sentinel) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/utils/aiter.py", line 78, in anext_impl return await __anext__(iterator) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform async for ichunk in input: File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform async for ichunk in input: File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1314, in atransform async for ichunk in input: File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 875, in astream yield await self.ainvoke(input, config, **kwargs) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langgraph/utils/runnable.py", line 373, in ainvoke ret = await self.afunc(*args, **kwargs) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/tablegpt/agent/data_analyzer.py", line 252, in agent_node agent_outcome: AgentAction | AgentFinish = await agent.ainvoke( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2923, in ainvoke input = await asyncio.create_task(part()) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 298, in ainvoke llm_result = await self.agenerate_prompt( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 787, in agenerate_prompt return await self.agenerate( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 747, in agenerate raise exceptions[0] File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 923, in _agenerate_with_cache result = await self._agenerate( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 843, in _agenerate response = await self.async_client.create(**payload) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/openai/resources/chat/completions/completions.py", line 2000, in create return await self._post( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/openai/_base_client.py", line 1767, in post return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls) File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/openai/_base_client.py", line 1461, in request return await self._request( File "/Users/penho/anaconda3/envs/py10/lib/python3.10/site-packages/openai/_base_client.py", line 1562, in _request raise self._make_status_error_from_response(err.response) from None openai.UnprocessableEntityError: Error code: 422 - {'detail': [{'type': 'string_type', 'loc': ['body', 'messages', 2, 'tool_calls'], 'msg': 'Input should be a valid string', 'input': [{'type': 'function', 'id': '82c06585-d765-4ebb-a5c8-c3c820880cec', 'function': {'name': 'python', 'arguments': '{"query": "# Load the data into a DataFrame\\ndf = read_df(\'titanic.csv\')\\n\\n# Remove leading and trailing whitespaces in column names\\ndf.columns = df.columns.str.strip()\\n\\n# Remove rows and columns that contain only empty values\\ndf = df.dropna(how=\'all\').dropna(axis=1, how=\'all\')\\n\\n# Get the basic information of the dataset\\ndf.info(memory_usage=False)"}'}}]}, {'type': 'string_type', 'loc': ['body', 'messages', 3, 'content'], 'msg': 'Input should be a valid string', 'input': [{'type': 'text', 'text': "```pycon\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 4 entries, 0 to 3\nData columns (total 8 columns):\n # Column Non-Null Count Dtype \n--- ------ -------------- ----- \n 0 Pclass 4 non-null int64 \n 1 Sex 4 non-null object \n 2 Age 4 non-null float64\n 3 SibSp 4 non-null int64 \n 4 Parch 4 non-null int64 \n 5 Fare 4 non-null float64\n 6 Embarked 4 non-null object \n 7 Survived 4 non-null int64 \ndtypes: float64(2), int64(4), object(2)\n```"}]}, {'type': 'string_type', 'loc': ['body', 'messages', 4, 'tool_calls'], 'msg': 'Input should be a valid string', 'input': [{'type': 'function', 'id': '36cd0e37-700a-422b-b6b9-fe32d6bdbf8d', 'function': {'name': 'python', 'arguments': '{"query": "# Show the first 5 rows to understand the structure\\ndf.head(5)"}'}}]}, {'type': 'string_type', 'loc': ['body', 'messages', 5, 'content'], 'msg': 'Input should be a valid string', 'input': [{'type': 'text', 'text': '```pycon\n Pclass Sex Age SibSp Parch Fare Embarked Survived\n0 2 female 29.0 0 2 23.000 S 1\n1 3 female 39.0 1 5 31.275 S 0\n2 3 male 26.5 0 0 7.225 C 0\n3 3 male 32.0 0 0 56.496 S 1\n```'}]}]} ``

我的代码如下：值修改了llm引用那一行，
`import asyncio
from datetime import date
from typing import TypedDict

from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from pybox import AsyncLocalPyBoxManager
from tablegpt import DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR
from tablegpt.agent import create_tablegpt_graph
from tablegpt.agent.file_reading import Stage


class Attachment(TypedDict):
    """Contains at least one dictionary with the key filename."""

    filename: str
    """The dataset uploaded in this session can be a filename, file path, or object storage address."""


# tablegpt-agent fully supports async invocation
async def main() -> None:
    llm = ChatOpenAI(openai_api_base="http://192.168.38.28:32336/v1", openai_api_key="whatever", model_name="qwen-7B")
    # llm = ChatOpenAI(openai_api_base="YOUR_VLLM_URL", openai_api_key="whatever", model_name="TableGPT2-7B")

    # Use local pybox manager for development and testing
    pybox_manager = AsyncLocalPyBoxManager(profile_dir=DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR)

    agent = create_tablegpt_graph(
        llm=llm,
        pybox_manager=pybox_manager,
        # We use MemorySaver as a checkpointer to record memory automatically.
        # See <https://langchain-ai.github.io/langgraph/concepts/persistence>
        checkpointer=MemorySaver(),
        # All code generated in this run will be executed in the kernel with kernel_id 'some-session-id'.
        session_id="some-session-id",
    )

    attachment_msg = HumanMessage(
        content="",
        # The dataset can be viewed in examples/datasets/titanic.csv.
        additional_kwargs={"attachments": [Attachment(filename="titanic.csv")]},
    )
    await agent.ainvoke(
        input={
            "entry_message": attachment_msg,
            "processing_stage": Stage.UPLOADED,
            "messages": [attachment_msg],
            "parent_id": "some-parent-id1",
            "date": date.today(),  # noqa: DTZ011
        },
        config={
            "configurable": {"thread_id": "some-thread-id"},
        },
    )

    human_message = HumanMessage(content="How many men survived?")

    async for event in agent.astream_events(
        input={
            # After using checkpoint, you only need to add new messages here.
            "messages": [human_message],
            "parent_id": "some-parent-id2",
            "date": date.today(),  # noqa: DTZ011
        },
        version="v2",
        # We configure the same thread_id to use checkpoints to retrieve the memory of the last run.
        config={"configurable": {"thread_id": "some-thread-id"}},
    ):
        print(event)  # noqa: T201


asyncio.run(main())`

**Comment by edwardzjl** [comment]
@pen-ho 麻烦另开一个新的 issue，谢谢

**Comment by pen-ho** [comment]
> [@pen-ho](https://github.com/pen-ho) 麻烦另开一个新的 issue，谢谢

好的
