### ISSUE TITLE
快速开始时，设置LLM服务报错

### ISSUE THREAD

**Issue by Cassie-Zhu-Shiying** [tablegpt/tablegpt-agent#172]
命令行：python -m vllm.entrypoints.openai.api_server --served-model-name TableGPT2-7B --model path/to/weights

错误：
Traceback (most recent call last):
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'path/to/weights'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 476, in <module>
    asyncio.run(run_server(args))
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 443, in run_server
    async with build_async_engine_client(args) as async_engine_client:
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 117, in build_async_engine_client
    if (model_is_embedding(args.model, args.trust_remote_code,
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 71, in model_is_embedding
    return ModelConfig(model=model_name,
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/vllm/config.py", line 169, in __init__
    self.hf_config = get_config(self.model, trust_remote_code, revision,
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 64, in get_config
    config = AutoConfig.from_pretrained(
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1021, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/transformers/configuration_utils.py", line 590, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/transformers/configuration_utils.py", line 649, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/deeplearning/yes/envs/tablegpt/lib/python3.10/site-packages/transformers/utils/hub.py", line 469, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'path/to/weights'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by edwardzjl** [comment]
`path/to/weights` 需要指向您下载的权重路径，或者使用 `tablegpt/TableGPT2-7B` (第一次加载的时候会比较慢因为会下载权重，需要能够访问 huggingface 的网络)

**Comment by Cassie-Zhu-Shiying** [comment]
> `path/to/weights`需要指向您下载的权重路径，或者使用 （第一次加载的时候会比较慢因为会下载权重，需要能够访问 huggingface 的网络）`tablegpt/TableGPT2-7B`

您好，连接不了huggingface，想从hf-mirror.com页面直接手动下载模型和权重的话，文件路径需要如何部署呢？

**Comment by edwardzjl** [comment]
一样的，从 <https://hf-mirror.com> 下载权重后，将 `python -m vllm.entrypoints.openai.api_server --served-model-name TableGPT2-7B --model path/to/weights` 里的 `path/to/weights` 改为您下载的权重位置。

**Comment by Cassie-Zhu-Shiying** [comment]
下载模型权重后，仍旧报错如下，是权重目录有问题吗？
python -m vllm.entrypoints.openai.api_server --served-model-name TableGPT2-7B --model TableGPT2-7B
WARNING 12-23 16:28:53 _custom_ops.py:17] Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')
段错误 (核心已转储)

![Snipaste_2024-12-23_16-33-04](https://github.com/user-attachments/assets/45d98e84-700e-4d11-87ab-dbda9491dfba)

**Comment by edwardzjl** [comment]
这个是 import error，一般是环境安装出现了问题。
建议给 vllm 服务单独一个干净的 venv，重新安装 vllm 之后再启动服务试试。
