### ISSUE TITLE
pydantic.errors.PydanticUserError: The `__modify_schema__` method is not supported in Pydantic v2. Use `__get_pydantic_json_schema__` instead in class `SecretStr`.

### ISSUE THREAD

**Issue by lllyyyqqq** [tablegpt/tablegpt-agent#85]
您好，我拉了最新的代码，跑data_analysis.py时法师如下报错：
/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/langchain_openai/chat_models/__init__.py:1: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet. 	from pydantic.v1 import BaseModel

  from langchain_openai.chat_models.azure import AzureChatOpenAI
/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/home/XXX/multi_summarization/mycode/tablegpt-agent/examples/data_analysis.py", line 6, in <module>
    from langchain_openai import ChatOpenAI
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/langchain_openai/__init__.py", line 1, in <module>
    from langchain_openai.chat_models import (
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/langchain_openai/chat_models/__init__.py", line 1, in <module>
    from langchain_openai.chat_models.azure import AzureChatOpenAI
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/langchain_openai/chat_models/azure.py", line 14, in <module>
    from langchain_openai.chat_models.base import BaseChatOpenAI
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 296, in <module>
    class BaseChatOpenAI(BaseChatModel):
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 224, in __new__
    complete_model_class(
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 577, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/main.py", line 671, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 739, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 739, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1115, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1308, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2107, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 657, in generate_schema
    metadata_js_function = _extract_get_pydantic_json_schema(obj, schema)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/envs/tablegpt/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2447, in _extract_get_pydantic_json_schema
    raise PydanticUserError(
pydantic.errors.PydanticUserError: The `__modify_schema__` method is not supported in Pydantic v2. Use `__get_pydantic_json_schema__` instead in class `SecretStr`.

For further information visit https://errors.pydantic.dev/2.9/u/custom-json-schema
ERROR conda.cli.main_run:execute(49): `conda run python /home/XXX/multi_summarization/mycode/tablegpt-agent/examples/data_analysis.py` failed. (See above for error)

麻烦看下怎么解决呢

**Comment by edwardzjl** [comment]
你的环境里是不是有安装 pydantic v1
tablegpt-agent 不支持 pydantic v1
建议创建一个新的虚拟环境安装 tablegpt-agent 再跑 quickstart

**Comment by lllyyyqqq** [comment]
我升级langchain-opeinai后跑通了quickstart。但是在跑data_analysis时，又遇到了ImportError: cannot import name 'DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR' from 'tablegpt'

**Comment by zTaoplus** [comment]
> 我升级langchain-opeinai后跑通了quickstart。但是在跑data_analysis时，又遇到了ImportError: cannot import name 'DEFAULT_TABLEGPT_IPYKERNEL_PROFILE_DIR' from 'tablegpt'

很抱歉，因为最新的代码还未发布，您可以使用下面的命令来安装最新的代码
```sh
pip install "git+https://github.com/tablegpt/tablegpt-agent@main#egg=tablegpt-agent[local]"
```

**Comment by edwardzjl** [comment]
已发布 0.2.14 版，包含了上述改动

**Comment by lllyyyqqq** [comment]
安装了新版，已跑通

**Comment by edwardzjl** [comment]
好的，那这个 issue 我先关闭了。

**Comment by yhl41001** [comment]
> 安装了新版，已跑通

@edwardzjl @lllyyyqqq 你好，请问langgraph版本是多少，我的pydantic 版本是 v2，会报同样错误。

**Comment by edwardzjl** [comment]
@yhl41001 能提供具体的报错内容吗？issue 一开始报的错是 pydantic v1 的错，如果你安装的是 pydantic v2 的话不应该报一样的错。

**Comment by lllyyyqqq** [comment]
> > 安装了新版，已跑通
> 
> @edwardzjl @lllyyyqqq 你好，请问langgraph版本是多少，我的pydantic 版本是 v2，会报同样错误。

![1733712139813](https://github.com/user-attachments/assets/6411f20c-a8ee-4dfc-9664-75d69d5f957b)
![1733712145483](https://github.com/user-attachments/assets/b7147753-d4e7-4926-9307-a72cc488a9cd)

**Comment by lllyyyqqq** [comment]
> > 安装了新版，已跑通
> 
> @edwardzjl @lllyyyqqq 你好，请问langgraph版本是多少，我的pydantic 版本是 v2，会报同样错误。

![1733712139813](https://github.com/user-attachments/assets/5e30f08a-1518-4199-953f-098bf1e5a615)
![1733712145483](https://github.com/user-attachments/assets/71d8972e-67f2-4bf5-8b11-024bd305d426)

**Comment by lllyyyqqq** [comment]
> > 安装了新版，已跑通
> 
> @edwardzjl @lllyyyqqq 你好，请问langgraph版本是多少，我的pydantic 版本是 v2，会报同样错误。

![1733712251396](https://github.com/user-attachments/assets/68a1b54f-ae24-4bce-a807-671dfceae09c)
![1733712145483](https://github.com/user-attachments/assets/2ab9b446-a3fc-42fa-aef1-6d9f305bfce4)

**Comment by yhl41001** [comment]
好的，多谢，我是之前用的环境管理方法错了，我再研究一下！
